export const topics = [
  "History",
  "Science",
  "Literature",
  "Dungeons and Dragons",
  "Geography",
  "Music",
  "Movies",
  "Television Shows",
  "Sports",
  "Technology",
  "Art",
  "Mythology",
  "Astronomy",
  "Biology",
  "Chemistry",
  "Physics",
  "Mathematics",
  "Environmental Science",
  "Medicine",
  "Nutrition",
  "Psychology",
  "Sociology",
  "Economics",
  "Political Science",
  "Philosophy",
  "Languages",
  "World Cultures",
  "Cooking",
  "Fashion",
  "Architecture",
  "Gardening",
  "Animal Kingdom",
  "Plants and Botany",
  "Marine Biology",
  "Meteorology",
  "Geology",
  "Archaeology",
  "Classical Music",
  "Jazz Music",
  "Rock Music",
  "Pop Music",
  "Hip-Hop Music",
  "Electronic Music",
  "Folk Music",
  "Country Music",
  "World Music",
  "Film History",
  "Animation",
  "Documentary Films",
  "Horror Movies",
  "Sci-Fi and Fantasy Movies",
  "Comedy Movies",
  "Drama Movies",
  "Action and Adventure Movies",
  "Silent Films",
  "Musical Theatre",
  "Opera",
  "Ballet",
  "Painting",
  "Sculpture",
  "Photography",
  "Comics and Graphic Novels",
  "Video Games",
  "Board Games",
  "Card Games",
  "Puzzles and Brain Teasers",
  "Magic and Illusion",
  "Circus Arts",
  "Street Art",
  "Digital Art",
  "Renaissance Art",
  "Baroque Art",
  "Impressionism",
  "Modern Art",
  "Contemporary Art",
  "Ancient Civilizations",
  "Medieval History",
  "Renaissance History",
  "Modern History",
  "Contemporary History",
  "American History",
  "European History",
  "Asian History",
  "African History",
  "Latin American History",
  "Middle Eastern History",
  "Australian History",
  "Canadian History",
  "Russian History",
  "Chinese History",
  "Indian History",
  "Egyptian History",
  "Roman History",
  "Greek History",
  "Viking History",
  "World Wars",
  "Cold War",
  "Space Exploration",
  "Inventions and Discoveries",
  "Nobel Prize Winners",
  "Olympic Games",
  "FIFA World Cup",
  "Tennis Grand Slams",
  "Basketball",
  "Baseball",
  "American Football",
  "Soccer",
  "Hockey",
  "Golf",
  "Motorsports",
  "Cycling",
  "Skateboarding",
  "Surfing",
  "Winter Sports",
  "Martial Arts",
  "Boxing",
  "Wrestling",
  "Yoga",
  "Pilates",
  "Fitness and Bodybuilding",
  "Dance Styles",
  "Travel and Landmarks",
  "National Parks",
  "World Festivals",
  "Wine",
  "Beer",
  "Spirits and Cocktails",
  "Coffee and Tea",
  "Baking",
  "Vegetarian and Vegan Cuisine",
  "World Cuisines",
  "Celebrity Chefs",
  "Fashion Designers",
  "Fashion Decades",
  "Beauty and Makeup",
  "Hairstyles",
  "Textiles and Patterns",
  "Famous Buildings",
  "Bridges",
  "Castles",
  "Ancient Monuments",
  "Skyscrapers",
  "Interior Design",
  "Tiny Houses",
  "Sustainable Living",
  "Pets",
  "Wild Animals",
  "Endangered Species",
  "Dinosaurs",
  "Insects",
  "Birds",
  "Reptiles and Amphibians",
  "Fish",
  "Trees",
  "Flowers",
  "Fungi",
  "National Flowers",
  "Coral Reefs",
  "Weather Phenomena",
  "Volcanoes",
  "Earthquakes",
  "Fossils",
  "Precious Stones and Minerals",
  "Famous Explorers",
  "Pirate History",
  "Kings and Queens",
  "World Leaders",
  "Revolutions and Uprisings",
  "Famous Battles",
  "Intelligence Agencies",
  "Spy Stories",
  "Mythical Creatures",
  "Fairy Tales",
  "Classic Novels",
];
